from backend.app.models.evidence import Evidence


def build_behavioral_evidence(
    inference: dict,
    confidence: float,
) -> Evidence:
    """
    Convert a behavioral inference into an Evidence object.

    Behavioral conclusions generated by the system
    are represented as inference evidence rather
    than direct user statements.
    """

    direction = inference["direction"]

    if direction == "positive":
        relationship = "support"
    else:
        relationship = "contradict"

    return Evidence(
        user_id=inference.get(
            "user_id",
            "unknown",
        ),
        content=inference["inference"],
        evidence_type="inference",
        relationship=relationship,
        reliability=confidence,
        specificity=1.0,
        independence=1.0,
    )