from backend.app.memory.retrieval_engine import (
    retrieve_memories,
)

from backend.app.graph.graph_retriever import (
    retrieve_related_memories,
)


def calculate_graph_retrieval_score(
    memory,
    relationship_strength: float = 0.0,
) -> float:
    """
    Calculate the retrieval score for a memory
    discovered through the relationship graph.

    Graph retrieval considers:

    - relationship strength
    - memory strength
    - importance
    - confidence
    """

    score = (
        relationship_strength * 0.45
        + memory.strength * 0.25
        + memory.importance * 0.20
        + memory.confidence * 0.10
    )

    return round(
        min(1.0, max(0.0, score)),
        4,
    )


def calculate_hybrid_score(
    vector_score: float,
    graph_score: float,
) -> float:
    """
    Combine vector and graph retrieval signals.

    Vector retrieval provides semantic relevance.

    Graph retrieval provides relationship-based relevance.

    If both signals exist, they are combined using
    weighted scoring.

    Vector weight  = 60%
    Graph weight   = 40%
    """

    score = (
        vector_score * 0.60
        + graph_score * 0.40
    )

    return round(
        min(1.0, max(0.0, score)),
        4,
    )


def run_retrieval_pipeline(
    query,
    memories,
    graph,
):
    """
    Complete hybrid retrieval pipeline.

    Pipeline:

        Query
          ↓
        Vector Retrieval
          ↓
        Graph Retrieval
          ↓
        Merge Results
          ↓
        Hybrid Scoring
          ↓
        Ranking

    Guarantees:

    1. Forgotten memories are never retrieved.
    2. The same memory cannot appear twice.
    3. Vector and graph signals are preserved.
    4. Every result contains:
           - retrieval_score
           - vector_score
           - graph_score
           - relationship_strength
           - retrieval_source
    """

    # =========================================================
    # STEP 0 : FILTER RETRIEVABLE MEMORIES
    # =========================================================

    retrievable_memories = [
        memory
        for memory in memories
        if memory.status != "forgotten"
    ]

    # =========================================================
    # STEP 1 : VECTOR RETRIEVAL
    # =========================================================

    vector_results = retrieve_memories(
        query=query,
        memories=retrievable_memories,
        emotion_store=None,
    )

    # =========================================================
    # STEP 2 : GRAPH RETRIEVAL
    # =========================================================

    graph_results = retrieve_related_memories(
        graph=graph,
        memories=retrievable_memories,
        start_subject=query,
        max_depth=2,
    )

    # =========================================================
    # STEP 3 : MERGE RESULTS
    # =========================================================

    merged = {}

    # ---------------------------------------------------------
    # VECTOR RESULTS
    # ---------------------------------------------------------

    for item in vector_results:

        memory = item["memory"]

        if memory is None:
            continue

        if memory.status == "forgotten":
            continue

        memory_id = memory.id

        merged[memory_id] = {
            "memory": memory,

            # Score generated by vector retrieval
            "vector_score": item.get(
                "retrieval_score",
                0.0,
            ),

            # Semantic similarity itself
            "semantic_similarity": item.get(
                "semantic_similarity",
                0.0,
            ),

            # No graph signal yet
            "graph_score": 0.0,

            "relationship_strength": 0.0,

            "relationship": None,

            "retrieval_source": "vector",
        }

    # ---------------------------------------------------------
    # GRAPH RESULTS
    # ---------------------------------------------------------

    for item in graph_results:

        if isinstance(item, dict):

            memory = item.get("memory")

            relationship_strength = item.get(
                "relationship_strength",
                item.get("strength", 0.0),
            )

            relationship = item.get(
                "relationship",
                "related",
            )

        else:

            memory = item

            relationship_strength = 0.0

            relationship = "related"

        if memory is None:
            continue

        if memory.status == "forgotten":
            continue

        memory_id = memory.id

        graph_score = calculate_graph_retrieval_score(
            memory=memory,
            relationship_strength=relationship_strength,
        )
        print(
            f"[GRAPH] {memory.content} "
            f"| relationship={relationship} "
            f"| relationship_strength={relationship_strength:.4f} "
            f"| graph_score={graph_score:.4f}"
            )

        # -----------------------------------------------------
        # MEMORY ALREADY FOUND BY VECTOR RETRIEVAL
        # -----------------------------------------------------

        if memory_id in merged:

            merged[memory_id]["graph_score"] = (
                graph_score
            )

            merged[memory_id][
                "relationship_strength"
            ] = relationship_strength

            merged[memory_id][
                "relationship"
            ] = relationship

            merged[memory_id][
                "retrieval_source"
            ] = "hybrid"

        # -----------------------------------------------------
        # MEMORY FOUND ONLY THROUGH GRAPH
        # -----------------------------------------------------

        else:

            merged[memory_id] = {
                "memory": memory,

                "vector_score": 0.0,

                "semantic_similarity": 0.0,

                "graph_score": graph_score,

                "relationship_strength": (
                    relationship_strength
                ),

                "relationship": relationship,

                "retrieval_source": "graph",
            }

    # =========================================================
    # STEP 4 : CALCULATE FINAL HYBRID SCORES
    # =========================================================

    retrieved = []

    for item in merged.values():

        memory = item["memory"]

        if memory is None:
            continue

        if memory.status == "forgotten":
            continue

        vector_score = item.get(
            "vector_score",
            0.0,
        )

        graph_score = item.get(
            "graph_score",
            0.0,
        )

        # -----------------------------------------------------
        # HYBRID SCORE
        # -----------------------------------------------------

        if (
            vector_score > 0.0
            and graph_score > 0.0
        ):

            final_score = calculate_hybrid_score(
                vector_score,
                graph_score,
            )

        elif vector_score > 0.0:

            # Vector-only result
            final_score = vector_score

        else:

            # Graph-only result
            final_score = graph_score

        item["retrieval_score"] = final_score

        retrieved.append(item)

    # =========================================================
    # STEP 5 : FINAL SAFETY FILTER
    # =========================================================
    

    MIN_RELEVANCE_SCORE = 0.43
    MIN_SEMANTIC_SIMILARITY = 0.15
    # A graph relationship must be genuinely strong
    # before it can compensate for low semantic similarity.
    STRONG_RELATIONSHIP_THRESHOLD = 0.70

    retrieved = [
        item
        for item in retrieved
        if (
            item.get("memory") is not None
            and item["memory"].status != "forgotten"
            and item.get("retrieval_score", 0.0)
            >= MIN_RELEVANCE_SCORE
            and (
                # -------------------------------------------------
                # CASE 1 : Semantically relevant memory
                # -------------------------------------------------
                item.get("semantic_similarity", 0.0)
                >= MIN_SEMANTIC_SIMILARITY

                or

                # -------------------------------------------------
                # CASE 2 : Strong graph association
                # -------------------------------------------------
                (
                    item.get("retrieval_source") == "graph"
                    and item.get(
                        "relationship_strength",
                        0.0,
                    ) >= STRONG_RELATIONSHIP_THRESHOLD
            )
        )
    )
]

    # =========================================================
    # STEP 6 : FINAL RANKING
    # =========================================================

    retrieved.sort(
        key=lambda item: item.get(
            "retrieval_score",
            0.0,
        ),
        reverse=True,
    )

    return retrieved